# Generated by Django 5.2 on 2025-04-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
